{% set name = "vyper" %}
{% set version = "0.2.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vyper-{{ version }}.tar.gz
  sha256: 88218584ea57103833cdd66977ecd20845c1c2e809f86eaf2e7c51b570d06315

build:
  number: 0
  noarch: python
  entry_points:
    - vyper=vyper.cli.vyper_compile:_parse_cli_args
    - vyper-serve=vyper.cli.vyper_serve:_parse_cli_args
    - vyper-lll=vyper.cli.vyper_lll:_parse_cli_args
    - vyper-json=vyper.cli.vyper_json:_parse_cli_args
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - asttokens ==2.0.4
    - pycryptodome >=3.5.1,<4
    - python >=3.6
    - semantic_version ==2.8.5

test:
  imports:
    - vyper
    - vyper.ast
  commands:
    - pip check
    - vyper --help
    - vyper-serve --help
    - vyper-lll --help
    - vyper-json --help
  requires:
    - pip

about:
  home: https://github.com/vyperlang/vyper
  summary: 'Vyper: the Pythonic Programming Language for the EVM'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - fubuloubu
    - iamdefinitelyahuman
