{% set name = "vyper" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vyper-{{ version }}.tar.gz
  sha256: 3e50cd802696ea3f5e6ab1bf4c9a90a39c332591d416c99f3d2fa93d7d7ba394

build:
  number: 0
  noarch: python
  entry_points:
    - vyper=vyper.cli.vyper_compile:_parse_cli_args
    - vyper-serve=vyper.cli.vyper_serve:_parse_cli_args
    - vyper-lll=vyper.cli.vyper_lll:_parse_cli_args
    - vyper-json=vyper.cli.vyper_json:_parse_cli_args
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools-scm
  run:
    - asttokens ==2.0.5
    - cached-property ==1.5.2  # [py<38]
    - importlib-metadata  # [py<38]
    - pycryptodome >=3.5.1,<4
    - python
    - semantic_version ==2.8.5
    - wheel

test:
  imports:
    - vyper
    - vyper.ast
  commands:
    - pip check
    - vyper --help
    - vyper-serve --help
    - vyper-lll --help
    - vyper-json --help
  requires:
    - pip

about:
  home: https://github.com/vyperlang/vyper
  summary: 'Vyper: the Pythonic Programming Language for the EVM'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - fubuloubu
    - iamdefinitelyahuman
