{% set name = "vyper" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vyper-{{ version }}.tar.gz
  sha256: 8dc1f501caab417fb0ce9c68a6944587f0147ec7cc7d3889cf3a45c19466e489

build:
  number: 0
  skip: true  # [py2k or py<38 or py>=311]
  entry_points:
    - vyper=vyper.cli.vyper_compile:_parse_cli_args
    - vyper-serve=vyper.cli.vyper_serve:_parse_cli_args
    - vyper-ir=vyper.cli.vyper_ir:_parse_cli_args
    - vyper-json=vyper.cli.vyper_json:_parse_cli_args
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools-scm
  run:
    - asttokens ==2.0.5
    - pycryptodome >=3.5.1,<4
    - python
    - semantic_version >=2.10,<3
    - wheel

test:
  imports:
    - vyper
  commands:
    - pip check
    - vyper --help
    - vyper-serve --help
    - vyper-ir --help
    - vyper-json --help
  requires:
    - pip

about:
  home: https://github.com/vyperlang/vyper
  summary: 'Vyper: the Pythonic Programming Language for the EVM'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - fubuloubu
    - iamdefinitelyahuman
