{% set name = "vyper" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vyper-{{ version }}.tar.gz
  sha256: f23c3ddadb4a857b9bcc3af4b6df7f3a80ac3c4c81f723d1b2e78afa3e0f3ba6

build:
  number: 1
  skip: true  # [py2k or py<38 or py>=312]
  entry_points:
    - vyper=vyper.cli.vyper_compile:_parse_cli_args
    - vyper-serve=vyper.cli.vyper_serve:_parse_cli_args
    - vyper-ir=vyper.cli.vyper_ir:_parse_cli_args
    - vyper-json=vyper.cli.vyper_json:_parse_cli_args
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools-scm
  run:
    - asttokens ==2.0.5
    - pycryptodome >=3.5.1,<4
    - python
    - semantic_version ==2.8.5
    - wheel

test:
  imports:
    - vyper
  commands:
    - pip check
    - vyper --help
    - vyper-serve --help
    - vyper-ir --help
    - vyper-json --help
  requires:
    - pip

about:
  home: https://github.com/vyperlang/vyper
  summary: 'Vyper: the Pythonic Programming Language for the EVM'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spinoch
    - fubuloubu
    - iamdefinitelyahuman
